# Generated by Django 3.1.2 on 2020-11-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('te', '0004_auto_20201106_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pestiKorName', models.CharField(max_length=100, unique=True, verbose_name='품목명')),
                ('regCpntQnty', models.CharField(max_length=100, verbose_name='주성분함량')),
                ('pestiBrandName', models.CharField(max_length=50, verbose_name='제품명')),
                ('compName', models.CharField(max_length=50, verbose_name='제조사')),
                ('toxicName', models.CharField(max_length=50, verbose_name='인축독성')),
                ('fishToxicGubun', models.CharField(max_length=50, verbose_name='어독성')),
                ('useName', models.CharField(max_length=30, verbose_name='용도')),
                ('indictSymbl', models.CharField(max_length=30, verbose_name='작용기작')),
                ('cropName', models.CharField(max_length=30, verbose_name='작물')),
                ('diseaseWeedName', models.CharField(max_length=50, verbose_name='적용병해충')),
                ('pestiUse', models.CharField(max_length=100, verbose_name='사용적기 및 방법')),
                ('dilutUnit', models.CharField(max_length=50, verbose_name='희석배수(10a당 사용량)')),
                ('useSuittime', models.CharField(max_length=50, verbose_name='안전사용시기')),
                ('useNum', models.CharField(max_length=30, verbose_name='안전사용횟수')),
            ],
            options={
                'verbose_name': 'pest',
                'verbose_name_plural': 'pests',
            },
        ),
    ]
