# Generated by Django 3.1.2 on 2020-11-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('te', '0006_auto_20201113_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pest',
            name='slug',
        ),
    ]
