# Generated by Django 3.1.2 on 2020-11-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('te', '0007_remove_pest_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pest',
            name='compName',
            field=models.TextField(blank=True, verbose_name='제조사'),
        ),
        migrations.AlterField(
            model_name='pest',
            name='cropName',
            field=models.CharField(max_length=250, verbose_name='작물'),
        ),
        migrations.AlterField(
            model_name='pest',
            name='dilutUnit',
            field=models.CharField(max_length=250, verbose_name='희석배수(10a당 사용량)'),
        ),
        migrations.AlterField(
            model_name='pest',
            name='diseaseWeedName',
            field=models.CharField(max_length=250, verbose_name='적용병해충'),
        ),
        migrations.AlterField(
            model_name='pest',
            name='indictSymbl',
            field=models.TextField(blank=True, verbose_name='작용기작'),
        ),
        migrations.AlterField(
            model_name='pest',
            name='pestiBrandName',
            field=models.TextField(blank=True, verbose_name='제품명'),
        ),
        migrations.AlterField(
            model_name='pest',
            name='pestiKorName',
            field=models.TextField(blank=True, verbose_name='품목명'),
        ),
        migrations.AlterField(
            model_name='pest',
            name='pestiUse',
            field=models.TextField(blank=True, verbose_name='사용적기 및 방법'),
        ),
        migrations.AlterField(
            model_name='pest',
            name='regCpntQnty',
            field=models.TextField(blank=True, verbose_name='주성분함량'),
        ),
        migrations.AlterField(
            model_name='pest',
            name='useName',
            field=models.TextField(blank=True, verbose_name='용도'),
        ),
        migrations.AlterField(
            model_name='pest',
            name='useNum',
            field=models.CharField(max_length=250, verbose_name='안전사용횟수'),
        ),
        migrations.AlterField(
            model_name='pest',
            name='useSuittime',
            field=models.CharField(max_length=250, verbose_name='안전사용시기'),
        ),
    ]
