# Generated by Django 3.1.2 on 2020-11-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('te', '0008_auto_20201113_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='pest',
            name='name',
            field=models.CharField(default='pestinfo', max_length=250, unique=True),
        ),
    ]
