# Generated by Django 3.1.2 on 2020-11-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('te', '0009_pest_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pest',
            name='name',
        ),
    ]
