# Generated by Django 3.1.2 on 2020-11-13 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('te', '0010_remove_pest_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pest',
            options={},
        ),
    ]
