# Generated by Django 3.1.2 on 2020-11-13 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('te', '0011_auto_20201113_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pest',
            options={'verbose_name': 'pest', 'verbose_name_plural': 'pests'},
        ),
    ]
