# Generated by Django 3.1.2 on 2020-11-26 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('te', '0013_auto_20201126_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_image',
            name='name',
        ),
    ]
