# Generated by Django 3.1.2 on 2020-11-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('te', '0014_remove_upload_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_image',
            name='name',
            field=models.CharField(default='default_name', max_length=150),
        ),
    ]
